name: picker_view
description: A Flutter picker view like iOS UIPickerView support multiple pickers.
version: 1.0.2
homepage: https://github.com/sososdk/picker_view.git

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
